[workspace]
resolver = "2"
members = ["bootloader/*", "crates/*", "libs/*", "modules/*", "xtask"]

[workspace.package]
version = "0.0.0"
edition = "2021"
publish = false

[workspace.dependencies]
log = "0.4.20"
