[package]
name = "microdragon-rust"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
microdragon_interface = { path = "../../crates/interface" }
bootloader_api = "0.11.4"
