[package]
name = "logging"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
common = { path = "../common" }
limine = "0.1"
uart_16550 = "0.2"
log = "0.4"
noto-sans-mono-bitmap = "0.2"
