[package]
name = "microdragon_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.58", features = ["full"] }
quote = "1.0.35"
proc-macro2 = "1.0.79"
toml = "0.8.12"
