[package]
name = "platform-x86_64"
version = "0.0.0"
edition = "2021"

[dependencies]
acpi = { path = "../acpi" }
logging = { path = "../logging" }
common = { path = "../common" }
memory = { path = "../memory" }
x86_64 = "0.14"
raw-cpuid = "10.6"
bitflags = "2.1"
log = "0.4"
volatile = "0.4"