[package]
name = "config_macros"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
toml = "0.8"
proc-macro2 = "1.0"

[dev-dependencies]
syn = { version = "2.0", features = ["extra-traits"] }
